services:
  mysql:
    image: mysql:latest
    container_name: M4-FP
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    restart: unless-stopped
    volumes:
      - db_data:/var/lib/mysql

  redis:
    image: redis/redis-stack:latest
    container_name: redis-stack
    ports:
      - "6379:6379"
      - "8001:8001"
    restart: unless-stopped

volumes:
  db_data: